// frontend/src/components/ThemeToggle.tsx
import Toggle from "react-toggle";
import "react-toggle/style.css";
import "./ThemeToggle.css";

function ThemeToggle() {
  function toggleTheme() {
    document.body.classList.toggle("dark-mode");
  }
  return (
    <>
      <Toggle
        onChange={toggleTheme}
        icons={{
          checked: "☾",
          unchecked: "☼",
        }}
        className="theme-toggle"
      />
    </>
  );
}

export default ThemeToggle;

// client/src/lib/ThemeToggle.svelte
<script>
	import Toggle from 'svelte-toggle';
	function toggleTheme() {
		document.body.classList.toggle('dark-mode');
	}
</script>

<Toggle
	on:toggle={toggleTheme}
	hideLabel
	switchColor="var(--bg-color)"
	toggledColor="var(--text-color)"
	untoggledColor="var(--text-color)"
	width="100px;"
	off="☾"
	on="☼"
/>
