// frontend/src/lib/Board.svelte
<script>
	class GameCell {
		constructor() {
			this.isMine = false;
			this.isRevealed = false;
			this.flagged = false;
			this.hinted = false;
		}
	}

	/**
	 * @param {number} height
	 * @param {number} width
	 * @param {number} mines
	 */
	function generateBoard(height, width, mines) {
		let board = Array.from({ length: height }, () =>
			Array.from({ length: width }, () => new GameCell())
		);
		let minesRemaining = mines;
		while (minesRemaining > 0) {
			let row = Math.floor(Math.random() * height);
			let col = Math.floor(Math.random() * width);
			if (board[row][col].isMine) {
				continue;
			}
			board[row][col].isMine = true;
			minesRemaining--;
		}
		return board;
	}

	/**
	 * @param {GameCell[][]} board
	 */
	function calculateNumbers(board) {
		/**
		 * @param {number} row
		 * @param {number} col
		 */
		let height = board.length;
		let width = height > 0 ? board[0].length : 0;
		/**
		 * @param {number} row
		 * @param {number} col
		 */
		function isMine(row, col) {
			if (0 > row || row >= height || 0 > col || col >= width) {
				return 0;
			}
			if (board[row][col].isMine) {
				return 1;
			}
			return 0;
		}
		/**
		 * @param {number} row
		 * @param {number} col
		 */
		function countMines(row, col) {
			let res = 0;
			for (let i = row - 1; i <= row + 1; i++) {
				for (let j = col - 1; j <= col + 1; j++) {
					if (i == row && j == col) {
						continue;
					}
					res += isMine(i, j);
				}
			}
			return res;
		}
		let res = Array.from({ length: height }, () => Array.from({ length: width }, () => 0));
		for (let row = 0; row < height; row++) {
			for (let col = 0; col < width; col++) {
				res[row][col] = countMines(row, col);
			}
		}
		return res;
	}

	/**
	 * @param {GameCell[][]} board
	 */
	function checkFinished(board) {
		let height = board.length;
		let width = height > 0 ? board[0].length : 0;
		let wonFlag = true;
		for (let row = 0; row < height; row++) {
			for (let col = 0; col < width; col++) {
				const cell = board[row][col];
				if (cell.isRevealed && cell.isMine) {
					return true;
				}
				if (!cell.isRevealed && !cell.isMine) {
					wonFlag = false;
				}
			}
		}
		return wonFlag;
	}

	import Cell from '$lib/Cell.svelte';
	/**
	 * @type {number}
	 */
	export let height;
	/**
	 * @type {number}
	 */
	export let width;
	/**
	 * @type {number}
	 */
	export let mines;
	let board = generateBoard(height, width, mines);
	let adjNumbers = calculateNumbers(board);
	let firstClick = true;
	function resetGame() {
		board = generateBoard(height, width, mines);
		adjNumbers = calculateNumbers(board);
		firstClick = true;
	}
	resetGame();
	$: finished = checkFinished(board);
	/**
	 * @param {number} row
	 * @param {number} col
	 */
	function revealCell(row, col) {
		if (row < 0 || row >= height || col < 0 || col >= width) {
			return;
		}
		if (firstClick) {
			while (board[row][col].isMine) {
				resetGame();
			}
			firstClick = false;
		}
		if (finished || board[row][col].isRevealed || board[row][col].flagged) {
			return;
		}
		board[row][col].isRevealed = true;
		if (adjNumbers[row][col] == 0 && !board[row][col].isMine) {
			for (let i = row - 1; i < row + 2; i++) {
				for (let j = col - 1; j < col + 2; j++) {
					revealCell(i, j);
				}
			}
		}
	}
	/**
	 * @param {number} row
	 * @param {number} col
	 */
	function flagCell(row, col) {
		if (finished || board[row][col].isRevealed) {
			return;
		}
		board[row][col].flagged = !board[row][col].flagged;
	}

	async function getLeastLikelyCell() {
		class ApiCell {
			/**
			 * @param {boolean} revealed
			 * @param {number} adjacent
			 */
			constructor(revealed, adjacent) {
				this.isRevealed = revealed;
				this.adjacentMines = adjacent;
			}
		}
		let apiBoard = Array.from({ length: height }, () =>
			Array.from({ length: width }, () => new ApiCell(false, 0))
		);
		for (let row = 0; row < height; row++) {
			for (let col = 0; col < width; col++) {
				apiBoard[row][col].adjacentMines = adjNumbers[row][col];
				apiBoard[row][col].isRevealed = board[row][col].isRevealed;
			}
		}
		let requestBody = {
			height: height,
			width: width,
			board: apiBoard
		};
		let response = await fetch('/api/leastLikelyCell', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json'
			},
			body: JSON.stringify(requestBody)
		});
		/**
		 * @type {number[]}
		 */
		let result = await response.json();
		return result;
	}
	async function hint() {
		if (finished) {
			return;
		}
		/**
		 * @type {number[]}
		 */
		let coords = await getLeastLikelyCell();
		for (let row = 0; row < height; row++) {
			for (let col = 0; col < width; col++) {
				board[row][col].hinted = false;
			}
		}
		board[coords[0]][coords[1]].hinted = true;
	}

	async function aiReveal() {
		if (finished) {
			return;
		}
		/**
		 * @type {number[]}
		 */
		let coords = await getLeastLikelyCell();
		revealCell(coords[0], coords[1]);
	}

	async function aiPlay() {
		while (!finished) {
			await aiReveal();
			await new Promise((r) => setTimeout(r, 20));
		}
	}
</script>

<div id="container">
	<div id="board">
		{#each Array.from({ length: height }, (_, row) => row) as row}
			<div class="row">
				{#each Array.from({ length: width }, (_, col) => col) as col}
					<Cell
						adjacentMines={adjNumbers[row][col]}
						mine={board[row][col].isMine && finished}
						revealed={board[row][col].isRevealed}
						flagged={board[row][col].flagged}
						hinted={board[row][col].hinted}
						on:reveal={() => revealCell(row, col)}
						on:flagged={() => flagCell(row, col)}
					/>
				{/each}
			</div>
		{/each}
	</div>
	<div id="controls">
		<button on:click={resetGame}>⟳</button>
		<button on:click={hint}>💡</button>
		<button on:click={aiPlay}>▶</button>
	</div>
</div>

<style>
	#container {
		display: flex;
		flex-direction: column;
		width: fit-content;
	}
	#controls {
		display: flex;
		justify-content: center;
	}
	#board {
		display: flex;
		flex-direction: column;
		background-color: var(--board-color);
		border: var(--border-size);
	}
	.row {
		display: flex;
		flex-direction: row;
	}
	button {
		background-color: inherit;
		color: var(--text-color);
		border: none;
		font-family: 'Fira Code';
		font-size: 100pt;
		width: 100%;
		transition: 100ms;
	}
	button:hover {
		background-color: var(--button-hover-color);
	}
</style>

// frontend/src/components/Board.tsx
import Cell from "./Cell";
import "./Board.css";
import { ReactNode, useEffect, useState } from "react";
interface BoardProps {
  height: number;
  width: number;
  mines: number;
}

class GameCell {
  isMine: boolean;
  isRevealed: boolean;
  flagged: boolean;
  hinted: boolean;
  constructor() {
    this.isMine = false;
    this.isRevealed = false;
    this.flagged = false;
    this.hinted = false;
  }
}

function cloneBoard(board: GameCell[][]): GameCell[][] {
  return JSON.parse(JSON.stringify(board));
}

function Board(props: BoardProps) {
  function generateBoard(
    height: number,
    width: number,
    mines: number,
  ): GameCell[][] {
    let genBoard = Array.from({ length: height }, () =>
      Array.from({ length: width }, () => new GameCell()),
    );
    let minesRemaining = mines;
    while (minesRemaining > 0) {
      let row = Math.floor(Math.random() * height);
      let col = Math.floor(Math.random() * width);
      if (genBoard[row][col].isMine) {
        continue;
      }
      genBoard[row][col].isMine = true;
      minesRemaining--;
    }
    return genBoard;
  }
  function calculateNumbers(board: GameCell[][]): number[][] {
    let height = board.length;
    let width = height > 0 ? board[0].length : 0;
    function isMine(row: number, col: number) {
      if (0 > row || row >= height || 0 > col || col >= width) {
        return 0;
      }
      if (board[row][col].isMine) {
        return 1;
      }
      return 0;
    }
    function countMines(row: number, col: number): number {
      let res = 0;
      for (let i = row - 1; i <= row + 1; i++) {
        for (let j = col - 1; j <= col + 1; j++) {
          if (i == row && j == col) {
            continue;
          }
          res += isMine(i, j);
        }
      }
      return res;
    }
    let res = Array.from({ length: height }, () =>
      Array.from({ length: width }, () => 0),
    );
    for (let row = 0; row < height; row++) {
      for (let col = 0; col < width; col++) {
        res[row][col] = countMines(row, col);
      }
    }
    return res;
  }

  function checkFinished(board: GameCell[][]): boolean {
    let height = board.length;
    let width = height > 0 ? board[0].length : 0;
    let wonFlag = true;
    for (let row = 0; row < height; row++) {
      for (let col = 0; col < width; col++) {
        const cell = board[row][col];
        if (cell.isRevealed && cell.isMine) {
          return true;
        }
        if (!cell.isRevealed && !cell.isMine) {
          wonFlag = false;
        }
      }
    }
    return wonFlag;
  }

  const [board, setBoard] = useState<GameCell[][]>(
    generateBoard(props.height, props.width, props.mines),
  );
  const [adjNumbers, setAdjNumbers] = useState<number[][]>(
    calculateNumbers(board),
  );
  const [firstClick, setFirstClick] = useState<boolean>(true);
  const [finished, setFinished] = useState<boolean>(checkFinished(board));

  function updateBoard(newBoard: GameCell[][]) {
    setBoard(newBoard);
    setAdjNumbers(calculateNumbers(newBoard));
    setFinished(checkFinished(newBoard));
  }

  function revealCell(
    board: GameCell[][],
    row: number,
    col: number,
  ): GameCell[][] {
    if (row < 0 || row >= props.height || col < 0 || col >= props.width) {
      return board;
    }
    if (finished || board[row][col].isRevealed || board[row][col].flagged) {
      return board;
    }
    board[row][col].isRevealed = true;
    if (adjNumbers[row][col] == 0 && !board[row][col].isMine) {
      for (let i = row - 1; i < row + 2; i++) {
        for (let j = col - 1; j < col + 2; j++) {
          if (i == row && j == col) {
            continue;
          }
          board = revealCell(board, i, j);
        }
      }
    }
    return board;
  }

  function revealCellWrapper(row: number, col: number) {
    let newBoard = cloneBoard(board);
    if (firstClick) {
      while (newBoard[row][col].isMine) {
        newBoard = generateBoard(props.height, props.width, props.mines);
      }
      setFirstClick(false);
    }
    newBoard = revealCell(newBoard, row, col);
    updateBoard(newBoard);
  }

  function reset() {
    updateBoard(generateBoard(props.height, props.width, props.mines));
  }

  function flagCell(row: number, col: number) {
    let newBoard = cloneBoard(board);
    if (finished || board[row][col].isRevealed) {
      return;
    }
    newBoard[row][col].flagged = !newBoard[row][col].flagged;
    updateBoard(newBoard);
  }

  async function getLeastLikelyCell() {
    // TODO use API library
    class ApiCell {
      isRevealed: boolean;
      adjacentMines: number;
      constructor(revealed: boolean, adjacent: number) {
        this.isRevealed = revealed;
        this.adjacentMines = adjacent;
      }
    }
    let apiBoard = Array.from({ length: props.height }, () =>
      Array.from({ length: props.width }, () => new ApiCell(false, 0)),
    );
    for (let row = 0; row < props.height; row++) {
      for (let col = 0; col < props.width; col++) {
        apiBoard[row][col].adjacentMines = adjNumbers[row][col];
        apiBoard[row][col].isRevealed = board[row][col].isRevealed;
      }
    }
    let requestBody = {
      height: props.height,
      width: props.width,
      board: apiBoard,
    };
    let response = await fetch("/api/leastLikelyCell", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(requestBody),
    });
    let result = await response.json();
    return result;
  }

  async function hint() {
    if (finished) {
      return;
    }
    let newBoard = cloneBoard(board);
    let coords = await getLeastLikelyCell();
    for (let row = 0; row < props.height; row++) {
      for (let col = 0; col < props.width; col++) {
        newBoard[row][col].hinted = false;
      }
    }
    newBoard[coords[0]][coords[1]].hinted = true;
    updateBoard(newBoard);
  }

  async function aiReveal() {
    if (finished) {
      return;
    }
    let coords = await getLeastLikelyCell();
    revealCellWrapper(coords[0], coords[1]);
  }

  const [renderedCells, setRenderedCells] = useState<ReactNode[]>([]);
  function renderCells() {
    let cells = [];
    for (let row = 0; row < props.height; row++) {
      let rowArray = [];
      for (let col = 0; col < props.width; col++) {
        rowArray.push(
          <Cell
            mine={board[row][col].isMine}
            revealed={board[row][col].isRevealed}
            flagged={board[row][col].flagged}
            hinted={board[row][col].hinted}
            adjacentMines={adjNumbers[row][col]}
            onReveal={() => revealCellWrapper(row, col)}
            onFlagged={() => flagCell(row, col)}
            key={`${row}|${col}`}
          />,
        );
      }
      cells.push(
        <div className="row" key={`${row}`}>
          {rowArray}
        </div>,
      );
    }
    setRenderedCells(cells);
  }
  useEffect(renderCells, [board]);
  return (
    <>
      <div id="container">
        <div id="board">{renderedCells}</div>
        <div id="controls">
          <button className="board" onClick={reset}>
            ⟳
          </button>
          <button className="board" onClick={hint}>
            💡
          </button>
          <button className="board" onClick={aiReveal}>
            ▶
          </button>
        </div>
      </div>
    </>
  );
}

export default Board;
